from sqlalchemy.orm import Session
from app.database import SessionLocal, Base, engine
from app.api.models.aide import AideDB
from app.models import Lib

def seed_db():
    db: Session = SessionLocal()
    try:
        # Supprimer toutes les tables existantes pour s'assurer que le schéma est à jour
        Base.metadata.drop_all(bind=engine)
        # Créer toutes les tables définies dans les modèles
        Base.metadata.create_all(bind=engine)

        # Supprimer toutes les aides existantes pour éviter les doublons
        db.query(AideDB).delete()
        db.commit()
        print("Anciennes aides supprimées de la base de données.")

        aides_data = [
            AideDB(
                categorie="Nationale",
                nom="Permis à 1 € par jour",
                description="Prêt à taux zéro de 600 € à 1 200 € pour les jeunes de 15 à 25 ans. Remboursement 30 €/mois. +300 € si 2e présentation. Intérêts payés par l'État. Organisme: Banques partenaires / État. Actif en 2026. Cumulable.",
                url_demande=None,
                age_min=15,
                age_max=25,
                statut_requis=None,
                montant=1200.0,
            ),
            AideDB(
                categorie="Nationale",
                nom="CPF — Permis B (demandeurs d'emploi)",
                description="Aide via le Compte Personnel de Formation (CPF) pour les demandeurs d'emploi inscrits à France Travail. Jusqu'à 900 €. Reste à charge minimum 100 €. Restreint depuis le 20/02/2026. Organisme: Caisse des Dépôts. Cumulable.",
                url_demande="https://www.moncompteformation.gouv.fr",
                statut_requis=["demandeur_emploi"],
                inscrit_france_travail_requis=True,
                montant=900.0,
            ),
            AideDB(
                categorie="Nationale",
                nom="CPF — Permis B (salariés)",
                description="Aide via le Compte Personnel de Formation (CPF) pour les salariés, avec cofinancement obligatoire d'un tiers (employeur, OPCO, collectivité) de minimum 100 €. Jusqu'à 900 €. Restreint en 2026. Organisme: Caisse des Dépôts. Cumulable.",
                url_demande="https://www.moncompteformation.gouv.fr",
                statut_requis=["salarie"],
                montant=800.0,
            ),
            AideDB(
                categorie="Nationale",
                nom="CPF — Permis C/D (poids lourd, bus)",
                description="Aide via le Compte Personnel de Formation (CPF) pour les permis poids lourd (C/D). Accessible à tous les actifs (salariés, demandeurs d'emploi, indépendants). Montant selon solde CPF, souvent entre 1 500 € et 3 000 €. Non soumis aux restrictions 2026. Organisme: Caisse des Dépôts. Actif en 2026. Cumulable.",
                url_demande="https://www.moncompteformation.gouv.fr",
                statut_requis=["salarie", "demandeur_emploi", "interimaire", "salarie_hcr", "salarie_btp", "reserve_militaire", "snu", "autre"], # Assuming 'tous actifs' covers these
            ),
            AideDB(
                categorie="Nationale",
                nom="Aide France Travail (ex-Pôle Emploi)",
                description="Aide de France Travail (anciennement Pôle Emploi) pour les demandeurs d'emploi. Jusqu'à 1 200 €. Supprimée au 1er avril 2026. Demande possible avant le 31/03/2026. Permis nécessaire à la reprise d'emploi requis.",
                url_demande=None,
                statut_requis=["demandeur_emploi"],
                montant=1200.0,
            ),
    AideDB(
        categorie="Nationale",
        nom="Aide 500 € pour les apprentis",
        description="Aide de 500 € pour les apprentis majeurs en contrat d'apprentissage (18-29 ans). Supprimée par la loi de finances 2026 (JO 20/02/2026). Dossiers déposés avant le 21/02/2026 encore traités.",
        url_demande=None,
        age_min=18,
        age_max=29,
        statut_requis=["apprenti"],
        montant=500.0,
    ),
AideDB(
    categorie="Nationale",
    nom="CEJ — Contrat d'Engagement Jeune",
    description="Financement du permis possible dans le cadre du Contrat d'Engagement Jeune (CEJ) pour les jeunes de 16 à 25 ans sans emploi ni formation. Le permis doit être identifié comme un levier d'insertion. Organisme: France Travail / Mission Locale. Actif en 2026. Cumulable.",
    url_demande=None,
    age_min=16,
    age_max=25,
    statut_requis=["jeune_insertion"],
),
AideDB(
    categorie="Nationale",
    nom="SNU — Service National Universel",
    description="Code de la route gratuit et remboursement de la 1ère présentation (~30 €) pour les jeunes de 15 à 17 ans ayant effectué le séjour de cohésion du Service National Universel (SNU). Séjour de cohésion gratuit (hébergement, repas, transport inclus). Organisme: Ministère / SNU. Actif en 2026. Cumulable.",
    url_demande="https://www.snu.gouv.fr",
    age_min=15,
    age_max=17,
),
AideDB(
    categorie="Nationale",
    nom="Aide Réservistes militaires",
    description="Aide de 1 000 € pour les jeunes engagés dans la réserve militaire (jusqu'à 25 ans). Nécessite un minimum de 50 jours d'activité effectués et ne pas posséder le permis B. Organisme: Ministère des Armées. Actif en 2026. Cumulable.",
    url_demande=None,
    age_max=25,
    statut_requis=["reserve_militaire"],
),
AideDB(
    categorie="Sectorielle",
    nom="Pro BTP — Apprentis du bâtiment",
    description="Aide jusqu'à 600 € pour les apprentis du bâtiment et des travaux publics (15-29 ans). Maintenue en 2026. Selon conditions OPCO. Organisme: Pro BTP. Actif en 2026. Cumulable.",
    url_demande="https://www.probtp.com",
    age_min=15,
    age_max=29,
    statut_requis=["apprenti", "salarie_btp"],
),
AideDB(
    categorie="Sectorielle",
    nom="HCRprévoyance — Hôtels-Cafés-Restaurants",
    description="Aide variable pour les salariés de la branche Hôtels-Cafés-Restaurants (HCR). Conditions selon convention collective. Organisme: HCRprévoyance. Actif en 2026. Cumulable.",
    url_demande="https://www.hcrprevoyance.fr",
    statut_requis=["salarie_hcr"],
),
AideDB(
    categorie="Sectorielle",
    nom="FASTT — Atout Permis (intérimaires)",
    description="Microcrédit social accompagné et parcours d'accompagnement spécifique pour les salariés intérimaires. Non une subvention directe. Organisme: FASTT. Actif en 2026. Cumulable.",
    url_demande="https://www.fastt.org",
    statut_requis=["interimaire"],
),
AideDB(
    categorie="Sectorielle",
    nom="OPCO / branche professionnelle",
    description="Cofinancement du CPF variable selon l'OPCO de l'entreprise pour les salariés. Minimum 100 €. À négocier avec l'employeur ou le service RH. Organisme: OPCO de l'entreprise. Actif en 2026. Cumulable.",
    url_demande=None,
    statut_requis=["salarie"],
),
AideDB(
    categorie="Handicap",
    nom="AGEFIPH — Aide au surcoût permis B",
    description="Aide de l'AGEFIPH jusqu'à 600 € pour les travailleurs handicapés (RQTH) pour couvrir le surcoût lié au handicap pour le permis B (50% du coût). Demande avant engagement des frais. Organisme: AGEFIPH. Actif en 2026. Cumulable.",
    url_demande="https://www.agefiph.fr",
    handicap_requis=True,
),
AideDB(
    categorie="Handicap",
    nom="AGEFIPH — Aide à la mobilité (déplacements)",
    description="Aide de l'AGEFIPH jusqu'à 12 000 € pour les personnes reconnues handicapées pour les équipements adaptés, taxis, transports adaptés liés à l'emploi. Organisme: AGEFIPH. Actif en 2026. Cumulable.",
    url_demande="https://www.agefiph.fr",
    handicap_requis=True,
),
AideDB(
    categorie="Handicap",
    nom="PCH — Prestation de Compensation du Handicap",
    description="Prestation de Compensation du Handicap (PCH) pour les personnes handicapées. Peut couvrir l'aménagement de véhicule jusqu'à 10 000 € (surcoût au-delà de 1 500 €). Complémentaire à l'AGEFIPH. Organisme: Conseil Départemental (MDPH). Actif en 2026. Cumulable.",
    url_demande=None,
    handicap_requis=True,
),
AideDB(
    categorie="Régionale",
    nom="Île-de-France — Chèque permis LABAZ",
    description="Chèque permis LABAZ de la Région Île-de-France jusqu'à 1 300 € pour les jeunes en insertion (18-25 ans) résidant en Île-de-France. Conditions d'insertion requises. Organisme: Région Île-de-France. Actif en 2026. Cumulable.",
    url_demande="https://www.iledefrance.fr",
    age_min=18,
    age_max=25,
    region="Île-de-France",
    statut_requis=["jeune_insertion"],
),
AideDB(
    categorie="Régionale",
    nom="Occitanie — Carte Jeune Région (CAP ou Bac Pro)",
    description="Aide de la Région Occitanie jusqu'à 500 € pour les jeunes (16-20 ans) en dernière année de CAP ou Bac Pro, titulaires de la Carte Jeune Région Occitanie. Organisme: Région Occitanie. Actif en 2026. Cumulable.",
    url_demande="https://www.laregion.fr",
    age_min=16,
    age_max=20,
    region="Occitanie",
    statut_requis=["etudiant"],
),
AideDB(
    categorie="Régionale",
    nom="Grand Est — Formation qualifiante",
    description="Aide de 1 000 € de la Région Grand Est pour les jeunes (16-30 ans) en formation qualifiante. Le permis doit être lié au projet de formation. Organisme: Région Grand Est. Actif en 2026. Cumulable.",
    url_demande="https://www.grandest.fr",
    age_min=16,
    age_max=30,
    region="Grand Est",
    formation_qualifiante_requise=True,
),
AideDB(
    categorie="Régionale",
    nom="Nouvelle-Aquitaine — Aide insertion jeunes",
    description="Aide de la Région Nouvelle-Aquitaine de 400 € à 1 200 € pour les jeunes diplômés 2025 en insertion professionnelle (17-25 ans). Demande possible 2 mois après diplôme. Organisme: Région Nouvelle-Aquitaine. Actif en 2026. Cumulable.",
    url_demande="https://les-aides.nouvelle-aquitaine.fr",
    age_min=17,
    age_max=25,
    region="Nouvelle-Aquitaine",
    statut_requis=["jeune_insertion"],
),
AideDB(
    categorie="Régionale",
    nom="Auvergne-Rhône-Alpes — Aide jeunes",
    description="Aide directe de 150 € de la Région Auvergne-Rhône-Alpes pour les jeunes (17-19 ans) résidant en AuRA et inscrits au permis B. Possibilité d'aide complémentaire jusqu'à 500 € via PASS'Région (bénévolat). Organisme: Région AuRA. Actif en 2026. Cumulable.",
    url_demande="https://www.auvergnerhonealpes.fr",
    age_min=17,
    age_max=19,
    region="Auvergne-Rhône-Alpes", # Corrected region name
),
AideDB(
    categorie="Régionale",
    nom="PACA — Métropole Toulon Provence Méditerranée",
    description="Aide de la Métropole Toulon Provence Méditerranée (PACA) jusqu'à 550 € (plus 200 € complémentaire) pour les jeunes en insertion (18-25 ans) résidant dans la métropole TPM. Certaines communes peuvent ajouter une bourse communale. Organisme: Métropole TPM / Région PACA. Actif en 2026. Cumulable.",
    url_demande="https://www.metropoletpm.fr",
    age_min=18,
    age_max=25,
    region="Provence-Alpes-Côte d'Azur", # Assuming PACA region
    commune="Toulon", # Assuming TPM implies Toulon for a specific commune
    statut_requis=["jeune_insertion"],
),
AideDB(
    categorie="Régionale",
    nom="Bretagne — Aide régionale permis",
    description="Aide de la Région Bretagne pour les jeunes (16-25 ans) en insertion ou formation. Montant variable selon situation et dossier. Organisme: Région Bretagne. Actif en 2026. Cumulable.",
    url_demande="https://www.bretagne.bzh",
    age_min=16,
    age_max=25,
    region="Bretagne",
    statut_requis=["jeune_insertion", "etudiant"], # Corrected statut_requis
),
AideDB(
    categorie="Régionale",
    nom="Hauts-de-France",
    description="Aide de la Région Hauts-de-France jusqu'à 500 € pour les jeunes en insertion ou demandeurs d'emploi (16-25 ans). Dispositifs liés à l'insertion professionnelle. Organisme: Région Hauts-de-France. Actif en 2026. Cumulable.",
    url_demande="https://www.hautsdefrance.fr",
    age_min=16,
    age_max=25,
    region="Hauts-de-France",
    statut_requis=["jeune_insertion", "demandeur_emploi"], # Corrected statut_requis
),
AideDB(
    categorie="Régionale",
    nom="Autres régions (Normandie, Pays de la Loire, etc.)",
    description="Aide régionale variable (300-800 €) pour les jeunes et l'insertion. Chaque région a ses propres critères. Organisme: Conseil Régional. Statut variable en 2026. Cumulable.",
    url_demande=None,
    statut_requis=["jeune_insertion"],
),
AideDB(
    categorie="Départementale",
    nom="FAJ — Fonds d'Aide aux Jeunes",
    description="Fonds d'Aide aux Jeunes (FAJ) de 300 € à 1 000 € (variable selon département) pour les jeunes en difficulté d'insertion (18-25 ans). Évaluation au cas par cas. Versé directement à l'auto-école. Organisme: Conseil Départemental / Mission Locale. Actif en 2026. Cumulable.",
    url_demande=None,
    age_min=18,
    age_max=25,
    statut_requis=["jeune_insertion"],
),
AideDB(
    categorie="Départementale",
    nom="Nord (59) — Aide insertion",
    description="Aide à l'insertion du Département du Nord (59) jusqu'à 600 € pour les jeunes en insertion (18-25 ans) du Nord. Conditions d'insertion sociale ou professionnelle vérifiées. Organisme: Département du Nord. Actif en 2026. Cumulable.",
    url_demande="https://www.nordpass.fr",
    age_min=18,
    age_max=25,
    departement="Nord",
    statut_requis=["jeune_insertion"], # Corrected statut_requis
),
AideDB(
    categorie="Départementale",
    nom="Guadeloupe (971) — Aide demandeurs d'emploi",
    description="Aide du Département Guadeloupe (971) de 400 € pour les jeunes demandeurs d'emploi (18-25 ans) en Guadeloupe. Aide liée à l'insertion professionnelle. Organisme: Département Guadeloupe. Actif en 2026. Cumulable.",
    url_demande=None,
    age_min=18,
    age_max=25,
    departement="Guadeloupe",
    statut_requis=["demandeur_emploi"], # Corrected statut_requis
),
AideDB(
    categorie="Locale",
    nom="Clermont-Ferrand — Aide municipale",
    description="Aide municipale de 300 € de la Ville de Clermont-Ferrand pour les jeunes (18-25 ans) sous conditions de ressources. Organisme: Ville de Clermont-Ferrand. Actif en 2026. Cumulable.",
    url_demande=None,
    age_min=18,
    age_max=25,
    commune="Clermont-Ferrand",
),
AideDB(
    categorie="Locale",
    nom="Bourse au permis — Communes (national)",
    description="Bourse au permis de 300 € à 1 000 € proposée par plus de 500 communes participantes en France. En échange de 20 à 40h de bénévolat. Organisme: Mairie / CCAS. Actif en 2026. Cumulable.",
    url_demande=None,
),
AideDB(
    categorie="Sociale",
    nom="Microcrédit personnel accompagné",
    description="Microcrédit personnel accompagné jusqu'à 5 000 € (taux réduit) pour les personnes exclues du crédit bancaire classique. Accompagnement social inclus. Organisme: ADIE, Croix-Rouge, Secours Catholique, CCAS. Actif en 2026. Cumulable.",
    url_demande="https://www.adie.org",
    statut_requis=["demandeur_emploi", "jeune_insertion"], # Assuming these are often excluded
),
AideDB(
    categorie="Sociale",
    nom="Microcrédit FASTT (intérimaires)",
    description="Microcrédit accompagné du FASTT pour les salariés intérimaires exclus du crédit classique. Organisme: FASTT. Actif en 2026. Cumulable.",
    url_demande="https://www.fastt.org",
    statut_requis=["interimaire"],
),
AideDB(
    categorie="Sociale",
    nom="RSA — Prise en charge possible via CD ou ML",
    description="Prise en charge possible du permis via le Conseil Départemental ou la Mission Locale pour les bénéficiaires du RSA. Montant variable selon département (200-600 €). Le permis doit être identifié comme un levier d'insertion dans le contrat RSA. Organisme: Conseil Départemental / Mission Locale. Statut variable en 2026. Cumulable.",
    url_demande=None,
    rsa_requis=True,
),
AideDB(
    categorie="Sociale",
    nom="Aide CROUS / Université",
    description="Aide variable (souvent 200-500 €) du CROUS ou de l'Université pour les étudiants boursiers (18-26 ans). Certains CROUS et universités proposent des aides spécifiques au permis. Organisme: CROUS / Université. Statut variable en 2026. Cumulable.",
    url_demande=None,
    age_min=18,
    age_max=26,
    statut_requis=["etudiant"],
    boursier_requis=True, # Corrected boursier_requis
)
        ]

        db.add_all(aides_data)
        db.commit()
        print(f"{len(aides_data)} nouvelles aides ajoutées à la base de données.")

        LIBS = [
            {"key": "calculateur.status.lyceen", "fr": "Lycéen", "en": "High School Student"},
            {"key": "calculateur.status.etudiant", "fr": "Étudiant", "en": "Student"},
            {"key": "calculateur.status.apprenti", "fr": "Apprenti", "en": "Apprentice"},
            {"key": "calculateur.status.salarie", "fr": "Salarié", "en": "Employee"},
            {"key": "calculateur.status.chomeur", "fr": "Demandeur d'emploi", "en": "Job seeker"},
            {"key": "calculateur.status.autre", "fr": "Autre", "en": "Other"},
            {"key": "calculateur.error.age_missing", "fr": "Veuillez renseigner votre âge.", "en": "Please enter your age."},
            {"key": "calculateur.error.age_invalid", "fr": "Âge invalide.", "en": "Invalid age."},
            {"key": "calculateur.error.cp_missing", "fr": "Veuillez renseigner votre code postal.", "en": "Please enter your postal code."},
            {"key": "calculateur.error.cp_invalid", "fr": "Le code postal doit contenir 5 chiffres.", "en": "The postal code must contain 5 digits."},
            {"key": "calculateur.error.status_missing", "fr": "Veuillez sélectionner un statut.", "en": "Please select a status."},
            {"key": "calculateur.error.api", "fr": "Erreur de l'API", "en": "API Error"},
            {"key": "calculateur.error.api_fetch", "fr": "Impossible de calculer vos aides pour le moment. Veuillez réessayer plus tard.", "en": "Unable to calculate your aids at the moment. Please try again later."},
            {"key": "calculateur.title", "fr": "Calculateur d'aides", "en": "Aids Calculator"},
            {"key": "calculateur.subtitle", "fr": "Découvrez en 2 minutes les financements auxquels vous avez droit pour votre permis de conduire.", "en": "Discover in 2 minutes the financing you are entitled to for your driver's license."},
            {"key": "calculateur.step1", "fr": "1. Profil", "en": "1. Profile"},
            {"key": "calculateur.step2", "fr": "2. Situation", "en": "2. Situation"},
            {"key": "calculateur.label.age", "fr": "Quel est votre âge ?", "en": "What is your age?"},
            {"key": "calculateur.placeholder.age", "fr": "Ex: 18", "en": "Ex: 18"},
            {"key": "calculateur.label.cp", "fr": "Code postal de votre lieu de résidence", "en": "Postal code of your residence"},
            {"key": "calculateur.desc.cp", "fr": "Certaines aides dépendent de votre région ou département.", "en": "Some aids depend on your region or department."},
            {"key": "calculateur.placeholder.cp", "fr": "Ex: 75001", "en": "Ex: 75001"},
            {"key": "calculateur.btn.next", "fr": "Suivant", "en": "Next"},
            {"key": "calculateur.label.status", "fr": "Quelle est votre situation principale ?", "en": "What is your main situation?"},
            {"key": "calculateur.btn.submit", "fr": "Voir mes aides", "en": "See my aids"},
            {"key": "calculateur.result.title", "fr": "Voici les aides auxquelles vous pourriez avoir droit", "en": "Here are the aids you might be entitled to"},
            {"key": "calculateur.result.subtitle_part1", "fr": "Basé sur votre profil, vous pourriez économiser jusqu'à ", "en": "Based on your profile, you could save up to "},
            {"key": "calculateur.result.default_category", "fr": "Aide", "en": "Aid"},
            {"key": "calculateur.result.how_to_apply", "fr": "Comment en faire la demande", "en": "How to apply"},
            {"key": "calculateur.result.no_aides", "fr": "Désolé, aucune aide ne semble correspondre à votre profil actuel.", "en": "Sorry, no aid seems to match your current profile."},
            {"key": "calculateur.btn.compare", "fr": "Comparer les auto-écoles", "en": "Compare driving schools"},
            {"key": "calculateur.btn.recalculate", "fr": "Recalculer mon profil", "en": "Recalculate my profile"},
            {"key": "hero.badge", "fr": "100% Indépendant & Gratuit", "en": "100% Independent & Free"},
            {"key": "hero.title.part1", "fr": "Trouvez la meilleure auto-école et les aides pour ", "en": "Find the best driving school and aids to "},
            {"key": "hero.title.part2", "fr": "financer votre permis.", "en": "finance your driver's license."},
            {"key": "hero.subtitle", "fr": "Ne passez pas à côté de vos financements. Comparez les prix, vérifiez votre éligibilité aux aides, et choisissez votre auto-école en toute confiance.", "en": "Don't miss out on your financing. Compare prices, check your eligibility for aids, and choose your driving school with confidence."},
            {"key": "hero.btn.estimate", "fr": "Estimer mes aides (Gratuit)", "en": "Estimate my aids (Free)"},
            {"key": "hero.social_proof.count", "fr": "+10k", "en": "+10k"},
            {"key": "hero.social_proof.text", "fr": "Rejoint par +10 000 candidats", "en": "Joined by 10,000+ candidates"},
            {"key": "hero.simulator.title", "fr": "Simulateur rapide", "en": "Quick simulator"},
            {"key": "hero.simulator.subtitle", "fr": "Découvrez le montant de vos aides en 2 clics.", "en": "Discover the amount of your aids in 2 clicks."},
            {"key": "hero.simulator.age_label", "fr": "Votre âge :", "en": "Your age:"},
            {"key": "hero.simulator.status_label", "fr": "Votre situation :", "en": "Your situation:"},
            {"key": "hero.simulator.status.select", "fr": "Sélectionnez...", "en": "Select..."},
            {"key": "hero.simulator.status.etudiant", "fr": "Étudiant", "en": "Student"},
            {"key": "hero.simulator.status.apprenti", "fr": "Apprenti (- de 21 ans)", "en": "Apprentice (under 21)"},
            {"key": "hero.simulator.status.chomeur", "fr": "Demandeur d'emploi", "en": "Job seeker"},
            {"key": "hero.simulator.status.salarie", "fr": "Salarié", "en": "Employee"},
            {"key": "hero.simulator.result.label", "fr": "Aide estimée au permis", "en": "Estimated aid for the license"},
            {"key": "hero.simulator.result.disclaimer", "fr": "Montant purement indicatif. Cliquez sur le bouton pour faire une simulation complète et précise.", "en": "Purely indicative amount. Click the button to run a complete and accurate simulation."},
            {"key": "hero.aid.default", "fr": "--- €", "en": "--- €"},
            {"key": "hero.aid.apprenti", "fr": "500 €", "en": "500 €"},
            {"key": "hero.aid.chomeur", "fr": "Jusqu'à 1200 €", "en": "Up to 1200 €"},
            {"key": "hero.aid.jeune", "fr": "Jusqu'à 300 €", "en": "Up to 300 €"},
            {"key": "hero.aid.autre", "fr": "Jusqu'à 800 €", "en": "Up to 800 €"},
            {"key": "pillars.main_title", "fr": "Trois repères pour choisir sans angle mort.", "en": "Three benchmarks to choose with no blind spots."},
            {"key": "pillars.main_desc", "fr": "Nous vous offrons une transparence totale sur les prix, une centralisation de vos aides, et une vue claire sur les délais pour vous aider à faire le meilleur choix.", "en": "We offer total transparency on prices, centralization of your aids, and a clear view of deadlines to help you make the best choice."},
            {"key": "pillars.1.title", "fr": "Prix et délais lisibles", "en": "Clear prices and deadlines"},
            {"key": "pillars.1.desc", "fr": "Comparer les forfaits, les délais moyens et les critères qui changent vraiment le budget final.", "en": "Compare packages, average deadlines, and criteria that actually affect the final budget."},
            {"key": "pillars.2.title", "fr": "Aides en 2 minutes", "en": "Aids in 2 minutes"},
            {"key": "pillars.2.desc", "fr": "Estimer les financements possibles selon votre profil et lancer la première étape depuis le calculateur.", "en": "Estimate possible financing according to your profile and start the first step right from the calculator."},
            {"key": "pillars.3.title", "fr": "Indice de rapidité", "en": "Speed index"},
            {"key": "pillars.3.desc", "fr": "Classer les auto-écoles selon la réactivité et le délai réel avant l'examen.", "en": "Rank driving schools based on responsiveness and actual wait times before the exam."},
            {"key": "about.help.financing.title", "fr": "Aides au financement", "en": "Financing aids"},
            {"key": "about.help.financing.desc", "fr": "CPF, paiements fractionnés et offres promotionnelles des auto-écoles partenaires.", "en": "CPF, split payments, and promotional offers from partner driving schools."},
            {"key": "about.help.location.title", "fr": "Choix par localisation", "en": "Choice by location"},
            {"key": "about.help.location.desc", "fr": "Comparez les établissements proches de chez vous ou autour de votre position actuelle.", "en": "Compare establishments near you or around your current position."},
            {"key": "about.help.comparison.title", "fr": "Comparaison simplifiée", "en": "Simplified comparison"},
            {"key": "about.help.comparison.desc", "fr": "Budget, délai, type de permis et boîte de vitesse sont regroupés au même endroit.", "en": "Budget, timeframe, license type, and gearbox are grouped in one place."},
            {"key": "about.badge", "fr": "Aides", "en": "Aids"},
            {"key": "about.title", "fr": "Financer et choisir son auto-école plus sereinement", "en": "Finance and choose your driving school more serenely"},
            {"key": "about.subtitle", "fr": "Cette page évite le 404 du menu et pose la base de l'espace aides du produit.", "en": "This page avoids the 404 from the menu and lays the foundation for the product's aids section."},
            {"key": "about.btn.back", "fr": "Retour au comparateur", "en": "Back to comparator"},
            {"key": "comparer.permit.all", "fr": "Tous", "en": "All"},
            {"key": "comparer.permit.voiture", "fr": "Voiture (B)", "en": "Car (B)"},
            {"key": "comparer.permit.moto", "fr": "Moto (A)", "en": "Motorcycle (A)"},
            {"key": "comparer.permit.poids_lourd", "fr": "Poids lourd (C)", "en": "Heavy Vehicle (C)"},
            {"key": "comparer.sort.score", "fr": "Score", "en": "Score"},
            {"key": "comparer.sort.asc", "fr": "Prix bas", "en": "Low price"},
            {"key": "comparer.sort.desc", "fr": "Prix haut", "en": "High price"},
            {"key": "comparer.score.all", "fr": "Tous", "en": "All"},
            {"key": "comparer.score.all.helper", "fr": "Aucun minimum", "en": "No minimum"},
            {"key": "comparer.score.70.helper", "fr": "Bon match", "en": "Good match"},
            {"key": "comparer.score.80.helper", "fr": "Très bon", "en": "Very good"},
            {"key": "comparer.score.90.helper", "fr": "Excellent", "en": "Excellent"},
            {"key": "comparer.gear.all", "fr": "Toutes", "en": "All"},
            {"key": "comparer.gear.auto", "fr": "Boîte auto", "en": "Auto gearbox"},
            {"key": "comparer.gear.manuelle", "fr": "Boîte manuelle", "en": "Manual gearbox"},
            {"key": "comparer.card.score", "fr": "Score", "en": "Score"},
            {"key": "comparer.card.quote", "fr": "Devis", "en": "Quote"},
            {"key": "comparer.card.package", "fr": "Forfait", "en": "Package"},
            {"key": "comparer.card.calculated", "fr": "Score calculé avec prix, note, délai et distance.", "en": "Score calculated with price, rating, delay, and distance."},
            {"key": "comparer.card.details", "fr": "Voir détails", "en": "View details"},
            {"key": "comparer.match.90", "fr": "90+ Excellent", "en": "90+ Excellent"},
            {"key": "comparer.match.80", "fr": "80+ Très bon", "en": "80+ Very good"},
            {"key": "comparer.match.70", "fr": "70+ Bon", "en": "70+ Good"},
            {"key": "comparer.match.default", "fr": "À comparer", "en": "To compare"},
            {"key": "comparer.reasons.speed_fast", "fr": "Délai rapide", "en": "Fast delay"},
            {"key": "comparer.reasons.speed_medium", "fr": "Délai maîtrisé", "en": "Controlled delay"},
            {"key": "comparer.reasons.rating_excellent", "fr": "Très bien notée", "en": "Highly rated"},
            {"key": "comparer.reasons.rating_good", "fr": "Bonne note", "en": "Good rating"},
            {"key": "comparer.reasons.price_competitive", "fr": "Prix compétitif", "en": "Competitive price"},
            {"key": "comparer.reasons.price_high", "fr": "Budget plus élevé", "en": "Higher budget"},
            {"key": "comparer.reasons.distance_very_close", "fr": "Très proche", "en": "Very close"},
            {"key": "comparer.reasons.distance_close", "fr": "Proche", "en": "Close"},
            {"key": "comparer.filter.score.title", "fr": "Score global", "en": "Global score"},
            {"key": "comparer.filter.score.hint", "fr": "Prix, note, délai et distance pondérés ensemble.", "en": "Price, rating, delay, and distance weighted together."},
            {"key": "comparer.filter.radius.title", "fr": "Rayon d'action", "en": "Action radius"},
            {"key": "comparer.filter.radius.hint_active", "fr": "Autour de", "en": "Around"},
            {"key": "comparer.filter.radius.hint_inactive", "fr": "Choisissez une adresse pour activer le rayon.", "en": "Choose an address to activate the radius."},
            {"key": "comparer.filter.radius.max", "fr": "max", "en": "max"},
            {"key": "comparer.filter.radius.inactive", "fr": "inactif", "en": "inactive"},
            {"key": "comparer.filter.budget.title", "fr": "Budget", "en": "Budget"},
            {"key": "comparer.filter.budget.hint", "fr": "Fourchette minimum et maximum.", "en": "Minimum and maximum range."},
            {"key": "comparer.filter.permit.title", "fr": "Type de permis", "en": "License type"},
            {"key": "comparer.filter.permit.hint", "fr": "Voiture, moto ou poids lourd.", "en": "Car, motorcycle, or heavy vehicle."},
            {"key": "comparer.filter.sort.title", "fr": "Tri", "en": "Sort"},
            {"key": "comparer.filter.sort.hint", "fr": "Score par défaut, prix si besoin.", "en": "Score by default, price if needed."},
            {"key": "comparer.filter.gear.title", "fr": "Boîte", "en": "Gearbox"},
            {"key": "comparer.filter.gear.hint", "fr": "Automatique ou manuelle.", "en": "Automatic or manual."},
            {"key": "comparer.filter.reset", "fr": "Réinitialiser les filtres", "en": "Reset filters"},
            {"key": "comparer.filter.reset_short", "fr": "Réinitialiser", "en": "Reset"},
            {"key": "comparer.filter.default", "fr": "Filtres par défaut", "en": "Default filters"},
            {"key": "comparer.filter.updating", "fr": "Mise à jour...", "en": "Updating..."},
            {"key": "comparer.filter.result", "fr": "résultat", "en": "result"},
            {"key": "comparer.filter.results", "fr": "résultats", "en": "results"},
            {"key": "comparer.filter.close", "fr": "Fermer", "en": "Close"},
            {"key": "comparer.mobile_sheet.title", "fr": "Filtres", "en": "Filters"},
            {"key": "comparer.mobile_sheet.subtitle", "fr": "Score, rayon, budget et boîte.", "en": "Score, radius, budget, and gearbox."},
            {"key": "comparer.cards_area.error", "fr": "Impossible de charger les auto-écoles. Vérifiez l'API et votre connexion.", "en": "Unable to load driving schools. Check the API and your connection."},
            {"key": "comparer.cards_area.empty_1", "fr": "Aucune auto-école trouvée avec ces critères.", "en": "No driving school found with these criteria."},
            {"key": "comparer.cards_area.empty_2", "fr": "Essayez d'élargir le budget, le rayon ou le score minimum.", "en": "Try to widen the budget, the radius, or the minimum score."},
            {"key": "comparer.page.filters", "fr": "Filtres", "en": "Filters"},
            {"key": "comparer.page.results_near", "fr": "Résultats près de", "en": "Results near"},
            {"key": "comparer.page.results_score", "fr": "Résultats par score", "en": "Results by score"},
            {"key": "comparer.page.title", "fr": "Comparer les auto-écoles", "en": "Compare driving schools"},
            {"key": "comparer.page.results_count", "fr": "Résultats", "en": "Results"},
            {"key": "comparer.page.active_address", "fr": "Adresse active", "en": "Active address"},
            {"key": "comparer.page.active_address_desc_1", "fr": "Les résultats sont calculés autour de", "en": "Results are calculated around"},
            {"key": "comparer.page.inactive_address_desc", "fr": "Saisissez une adresse ou utilisez votre position pour activer le rayon. Sans adresse, le classement reste basé sur le score global.", "en": "Enter an address or use your position to activate the radius. Without an address, the ranking remains based on the global score."},
            {"key": "comparer.page.address", "fr": "Adresse", "en": "Address"},
            {"key": "comparer.page.desktop_title", "fr": "Trouvez l'établissement qui coche les bons critères", "en": "Find the establishment that ticks the right boxes"},
            {"key": "comparer.page.desktop_subtitle", "fr": "Adresse précise, rayon, budget et score global dans une interface plus lisible pour comparer vite.", "en": "Precise address, radius, budget, and global score in a more readable interface to compare quickly."},
            {"key": "comparer.page.desktop_schools", "fr": "Auto-écoles", "en": "Driving schools"},
            {"key": "comparer.page.radius_inactive", "fr": "Rayon inactif", "en": "Inactive radius"},
            {"key": "comparer.page.radius_inactive_desc", "fr": "Choisissez une adresse complète pour activer la proximité. Le classement actuel privilégie le score global.", "en": "Choose a complete address to activate proximity. The current ranking favors the overall score."},
            {"key": "comparer.summary.radius", "fr": "Rayon", "en": "Radius"},
            {"key": "comparer.summary.score", "fr": "Score", "en": "Score"},
            {"key": "comparer.summary.low_price", "fr": "Prix bas", "en": "Low price"},
            {"key": "comparer.summary.high_price", "fr": "Prix haut", "en": "High price"},
            {"key": "comparer.summary.auto", "fr": "Boîte auto", "en": "Auto gearbox"},
            {"key": "comparer.summary.manual", "fr": "Boîte manuelle", "en": "Manual gearbox"},
            {"key": "comparer.summary.sort_score", "fr": "Tri score", "en": "Sort by score"},
            {"key": "comparer.summary.gearbox", "fr": "Boîte", "en": "Gearbox"},
            {"key": "calculateur.status.jeune_insertion", "fr": "Jeune en insertion", "en": "Youth in integration"},
            {"key": "calculateur.status.interimaire", "fr": "Intérimaire", "en": "Temporary worker"},
            {"key": "calculateur.status.reserve_militaire", "fr": "Réserviste", "en": "Military reservist"},
            {"key": "calculateur.status.snu", "fr": "SNU", "en": "SNU (Universal National Service)"},
            {"key": "calculator_form.profile.title", "fr": "Votre profil", "en": "Your profile"},
            {"key": "calculator_form.profile.age", "fr": "Âge", "en": "Age"},
            {"key": "calculator_form.profile.region", "fr": "Région", "en": "Region"},
            {"key": "calculator_form.profile.status", "fr": "Statut actuel", "en": "Current status"},
            {"key": "calculator_form.specific.title", "fr": "Situations spécifiques", "en": "Specific situations"},
            {"key": "calculator_form.specific.rqth", "fr": "Êtes-vous en situation de handicap (RQTH) ?", "en": "Are you in a situation of disability (RQTH)?"},
            {"key": "calculator_form.specific.boursier", "fr": "Êtes-vous étudiant boursier ?", "en": "Are you a scholarship student?"},
            {"key": "calculator_form.specific.france_travail", "fr": "Êtes-vous inscrit à France Travail ?", "en": "Are you registered with France Travail?"},
            {"key": "calculator_form.specific.rsa", "fr": "Êtes-vous bénéficiaire du RSA ?", "en": "Are you a RSA beneficiary?"},
            {"key": "calculator_form.specific.formation", "fr": "Suivez-vous une formation qualifiante ?", "en": "Are you undergoing qualifying training?"},
            {"key": "calculator_form.btn.yes", "fr": "Oui", "en": "Yes"},
            {"key": "calculator_form.btn.no", "fr": "Non", "en": "No"},
            {"key": "calculator_form.btn.calculating", "fr": "Calcul en cours...", "en": "Calculating..."},
            {"key": "calculator_form.btn.estimate", "fr": "Estimer mes aides", "en": "Estimate my aids"},
            {"key": "calculator_results.total_potential", "fr": "Total potentiel des aides", "en": "Total potential aids"},
            {"key": "calculator_results.details_title", "fr": "Détails des aides éligibles", "en": "Details of eligible aids"},
            {"key": "calculator_results.view_details", "fr": "VOIR LES DÉTAILS", "en": "VIEW DETAILS"},
            {"key": "calculator_results.no_aids_found", "fr": "Aucune aide trouvée pour votre profil actuel.", "en": "No aids found for your current profile."},
            {"key": "calculator_results.disclaimer", "fr": "Cette simulation est basée sur les données publiques disponibles en 2026. Elle est fournie à titre indicatif et ne constitue pas une garantie d'obtention. Les critères réels et les montants finaux doivent être validés auprès des organismes officiels.", "en": "This simulation is based on public data available in 2026. It is provided for indicative purposes and does not constitute a guarantee of obtaining them. The actual criteria and final amounts must be validated with the official organizations."},
            {"key": "navbar.comparer", "fr": "Comparer", "en": "Compare"},
            {"key": "navbar.aides", "fr": "Aides", "en": "Aids"},
            {"key": "navbar.compte", "fr": "Compte", "en": "Account"},
            {"key": "compte.greeting", "fr": "Bonjour", "en": "Hello"},
            {"key": "compte.welcome", "fr": "Bienvenue sur votre espace personnel.", "en": "Welcome to your personal space."},
            {"key": "compte.logout", "fr": "Se déconnecter", "en": "Log out"},
            {"key": "compte.info.title", "fr": "Mes informations", "en": "My information"},
            {"key": "compte.info.fullname", "fr": "Nom complet", "en": "Full name"},
            {"key": "compte.info.email", "fr": "Email", "en": "Email"},
            {"key": "compte.info.phone", "fr": "Téléphone", "en": "Phone"},
            {"key": "compte.info.age", "fr": "Âge", "en": "Age"},
            {"key": "compte.info.years", "fr": "ans", "en": "years"},
            {"key": "compte.info.status", "fr": "Statut", "en": "Status"},
            {"key": "compte.info.postal_code", "fr": "Code Postal", "en": "Postal Code"},
            {"key": "compte.soon", "fr": "Bientôt", "en": "Coming soon"},
            {"key": "compte.favorites.title", "fr": "Auto-écoles favorites", "en": "Favorite driving schools"},
            {"key": "compte.favorites.desc", "fr": "Vous pourrez bientôt sauvegarder vos auto-écoles préférées pour les comparer plus facilement et les retrouver sur tous vos appareils.", "en": "You will soon be able to save your favorite driving schools to compare them more easily and find them on all your devices."},
            {"key": "compte.favorites.empty", "fr": "Vous n'avez pas encore d'auto-école favorite. Cliquez sur le ❤️ d'une auto-école pour l'enregistrer.", "en": "You don't have any favorite driving school yet. Click the ❤️ on a driving school to save it."},
            {"key": "compte.history.title", "fr": "Historique des recherches", "en": "Search history"},
            {"key": "compte.history.desc", "fr": "Retrouvez facilement les résultats de vos précédentes recherches et calculs d'aides CPF / Pôle Emploi.", "en": "Easily find the results of your previous searches and CPF / Pôle Emploi aid calculations."},
            {"key": "compte.history.empty", "fr": "Aucune recherche enregistrée pour le moment.", "en": "No saved search yet."},
            {"key": "compte.history.potential", "fr": "Aides potentielles", "en": "Potential aids"},
            {"key": "compte.history.aides_count", "fr": "aide(s) éligible(s)", "en": "eligible aid(s)"},
            {"key": "auth.error.unexpected", "fr": "Une erreur inattendue est survenue, veuillez réessayer plus tard.", "en": "An unexpected error occurred, please try again later."},
            {"key": "auth.error.validation", "fr": "Le format de certaines informations est incorrect. Veuillez vérifier votre saisie.", "en": "The format of some information is incorrect. Please check your entry."},
            {"key": "auth.error.user_not_found", "fr": "Aucun compte n'a été trouvé avec cette adresse e-mail.", "en": "No account was found with this email address."},
            {"key": "auth.error.email_registered", "fr": "Cette adresse e-mail est déjà utilisée.", "en": "This email address is already in use."},
            {"key": "auth.error.otp_invalid", "fr": "Le code secret est incorrect ou a expiré.", "en": "The secret code is incorrect or has expired."},
            {"key": "auth.error.not_found", "fr": "Erreur technique : Adresse introuvable.", "en": "Technical error: Address not found."},
            {"key": "auth.title.login", "fr": "Connexion", "en": "Login"},
            {"key": "auth.title.register", "fr": "Inscription", "en": "Sign Up"},
            {"key": "auth.title.verify", "fr": "Vérification", "en": "Verification"},
            {"key": "auth.subtitle.login", "fr": "Entrez votre e-mail pour recevoir un code de connexion ou vous inscrire.", "en": "Enter your email to receive a login code or to sign up."},
            {"key": "auth.subtitle.register", "fr": "On dirait que vous êtes nouveau ! Complétons votre profil avant de continuer.", "en": "Looks like you're new here! Let's complete your profile before continuing."},
            {"key": "auth.subtitle.verify_part1", "fr": "Nous avons envoyé un code secret à", "en": "We have sent a secret code to"},
            {"key": "auth.subtitle.verify_part2", "fr": "Entrez-le ci-dessous.", "en": "Enter it below."},
            {"key": "auth.placeholder.email", "fr": "nom@exemple.fr", "en": "name@example.com"},
            {"key": "auth.btn.continue", "fr": "Continuer", "en": "Continue"},
            {"key": "auth.placeholder.firstname", "fr": "Prénom", "en": "First name"},
            {"key": "auth.placeholder.lastname", "fr": "Nom", "en": "Last name"},
            {"key": "auth.placeholder.phone", "fr": "Numéro de téléphone", "en": "Phone number"},
            {"key": "auth.btn.register", "fr": "S'inscrire et recevoir le code", "en": "Sign up and receive code"},
            {"key": "auth.placeholder.otp", "fr": "Code à 6 chiffres", "en": "6-digit code"},
            {"key": "auth.btn.verify", "fr": "Vérifier et se connecter", "en": "Verify and log in"}
        ]
        
        db.add_all([Lib(**data) for data in LIBS])
        db.commit()
        print(f"{len(LIBS)} traductions ajoutées à la base de données.")

    except Exception as e:
        db.rollback()
        print(f"Erreur lors du seeding de la base de données : {e}")
    finally:
        db.close()

if __name__ == "__main__":
    print("Démarrage du seeding de la base de données...")
    seed_db()
    print("Seeding terminé.")