from app.api.models.aide import AideDB
from app.database import SessionLocal
from app.models import AutoEcole, Lib


AIDES = [
    # ── Aides nationales ──────────────────────────────────────────────
    {
        "categorie": "Nationale",
        "nom": "Permis à 1 € par jour",
        "description": "Prêt à taux zéro dont les intérêts sont pris en charge par l'État. "
                       "Montant de 600 €, 800 €, 1 000 € ou 1 200 € selon la formation choisie. "
                       "Réservé aux jeunes de 15 à 25 ans, dans une auto-école labellisée.",
        "url_demande": "https://www.service-public.fr/particuliers/vosdroits/F13609",
        "age_min": 15,
        "age_max": 25,
        "statut_requis": None,
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 1200.0,
    },
    {
        "categorie": "Nationale",
        "nom": "Compte Personnel de Formation (CPF)",
        "description": "Utilisez vos droits CPF pour financer votre permis B, B1, A1 ou A2 (plafond 900 €). "
                       "Réservé aux demandeurs d'emploi ou salariés avec cofinancement employeur. "
                       "L'auto-école doit être certifiée Qualiopi.",
        "url_demande": "https://www.moncompteformation.gouv.fr/",
        "age_min": 16,
        "age_max": None,
        "statut_requis": ["salarie", "demandeur_emploi"],
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 900.0,
    },
    {
        "categorie": "Nationale",
        "nom": "Fonds d'Aide aux Jeunes (FAJ)",
        "description": "Aide départementale pour les jeunes de 18 à 25 ans en grande difficulté "
                       "d'insertion sociale ou professionnelle. Montant variable selon le département "
                       "(généralement entre 600 € et 1 200 €). Contactez votre Mission Locale.",
        "url_demande": None,
        "age_min": 18,
        "age_max": 25,
        "statut_requis": ["demandeur_emploi", "lyceen", "autre"],
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 800.0,
    },
    {
        "categorie": "Nationale",
        "nom": "Aide au permis pour les bénéficiaires du RSA",
        "description": "Certains départements proposent une aide au financement du permis pour "
                       "les bénéficiaires du RSA dans le cadre du parcours d'insertion. "
                       "Montant variable, souvent autour de 1 000 €.",
        "url_demande": None,
        "age_min": 18,
        "age_max": None,
        "statut_requis": None,
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": True,
        "formation_qualifiante_requise": False,
        "montant": 1000.0,
    },
    {
        "categorie": "Nationale",
        "nom": "Aide AGEFIPH pour les personnes en situation de handicap",
        "description": "L'AGEFIPH peut financer tout ou partie du permis de conduire pour les "
                       "personnes en situation de handicap (RQTH). Le montant peut aller jusqu'à 1 300 €.",
        "url_demande": "https://www.agefiph.fr/aides-handicap/aide-au-permis-de-conduire",
        "age_min": 18,
        "age_max": None,
        "statut_requis": None,
        "handicap_requis": True,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 1300.0,
    },
    {
        "categorie": "Nationale",
        "nom": "Bourse au permis de conduire",
        "description": "De nombreuses communes proposent une bourse au permis en échange d'heures "
                       "de bénévolat (en général 30 à 50h). Aide de 500 € à 800 € selon la commune. "
                       "Réservée aux jeunes de 18 à 25 ans.",
        "url_demande": None,
        "age_min": 18,
        "age_max": 25,
        "statut_requis": None,
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 600.0,
    },
    # ── Aides régionales Île-de-France ─────────────────────────────────
    {
        "categorie": "Régionale",
        "nom": "Aide au permis Île-de-France (lycéens/apprentis)",
        "description": "La Région Île-de-France propose une aide de 300 € pour les lycéens et "
                       "apprentis franciliens. Démarche via le portail mesdémarches.iledefrance.fr.",
        "url_demande": "https://mesdemarches.iledefrance.fr/",
        "age_min": 16,
        "age_max": 25,
        "region": "Île-de-France",
        "statut_requis": ["lyceen", "apprenti", "etudiant"],
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 300.0,
    },
    {
        "categorie": "Régionale",
        "nom": "FAJ Île-de-France renforcé",
        "description": "En Île-de-France, le Fonds d'Aide aux Jeunes peut être abondé par la région "
                       "pour aller jusqu'à 1 200 € pour les jeunes en insertion. "
                       "Contactez votre Mission Locale.",
        "url_demande": None,
        "age_min": 18,
        "age_max": 25,
        "region": "Île-de-France",
        "statut_requis": ["demandeur_emploi", "autre"],
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": True,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 1200.0,
    },
    # ── Aides régionales PACA ──────────────────────────────────────────
    {
        "categorie": "Régionale",
        "nom": "Aide au permis Région Sud (PACA)",
        "description": "La Région Sud propose une aide de 500 € pour les jeunes de 18 à 25 ans "
                       "résidant en Provence-Alpes-Côte d'Azur, sous conditions de ressources.",
        "url_demande": "https://www.maregionsud.fr/",
        "age_min": 18,
        "age_max": 25,
        "region": "Provence-Alpes-Côte d'Azur",
        "statut_requis": None,
        "handicap_requis": False,
        "boursier_requis": False,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 500.0,
    },
    # ── Aide spécifique étudiants boursiers ────────────────────────────
    {
        "categorie": "Nationale",
        "nom": "Aide spécifique étudiants boursiers",
        "description": "Certaines universités et CROUS proposent une aide au permis pour les étudiants "
                       "boursiers (échelons 5 à 7). Montant variable, en moyenne 500 €.",
        "url_demande": None,
        "age_min": 18,
        "age_max": 30,
        "statut_requis": ["etudiant"],
        "handicap_requis": False,
        "boursier_requis": True,
        "inscrit_france_travail_requis": False,
        "rsa_requis": False,
        "formation_qualifiante_requise": False,
        "montant": 500.0,
    },
]


ECOLES = [
    {
        "name": "Auto-école l'Avenir",
        "city": "Paris",
        "postal_code": "75015",
        "address": "12 rue de la Paix, Paris 15e",
        "lat": 48.8418,
        "lng": 2.2985,
        "rating": 4.8,
        "price": 899,
        "price_label": "Forfait complet",
        "speed_level": "rapide",
        "speed_label": "4-8 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Patient", "color": "blue"},
            {"label": "Pédagogue", "color": "blue"},
            {"label": "Dispo demain", "color": "green"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=600&auto=format&fit=crop",
    },
    {
        "name": "Shift Drive Academy",
        "city": "Boulogne-Billancourt",
        "postal_code": "92100",
        "address": "5 avenue André Morizet, Boulogne",
        "lat": 48.8350,
        "lng": 2.2403,
        "rating": 4.5,
        "price": 750,
        "price_label": "Code inclus",
        "speed_level": "moyen",
        "speed_label": "8-10 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Premium", "color": "blue"},
            {"label": "Rapide", "color": "blue"},
            {"label": "Boîte Auto", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&auto=format&fit=crop",
    },
    {
        "name": "École de Conduite Métro",
        "city": "Paris",
        "postal_code": "75013",
        "address": "45 boulevard Auguste Blanqui, Paris 13e",
        "lat": 48.8310,
        "lng": 2.3522,
        "rating": 4.3,
        "price": 820,
        "price_label": "Forfait 20h",
        "speed_level": "faible",
        "speed_label": "10-14 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Boîte Auto", "color": "blue"},
            {"label": "Flexible", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=600&auto=format&fit=crop",
    },
    {
        "name": "Cap Conduite",
        "city": "Issy-les-Moulineaux",
        "postal_code": "92130",
        "address": "3 rue Ernest Renan, Issy-les-Moulineaux",
        "lat": 48.8165,
        "lng": 2.2702,
        "rating": 4.6,
        "price": 780,
        "price_label": "Forfait 20h",
        "speed_level": "rapide",
        "speed_label": "5-7 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Expérimenté", "color": "blue"},
            {"label": "Boîte Auto", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop",
    },
    {
        "name": "Conduite Plus",
        "city": "Vincennes",
        "postal_code": "94300",
        "address": "18 cours Marigny, Vincennes",
        "lat": 48.8478,
        "lng": 2.4397,
        "rating": 4.2,
        "price": 850,
        "price_label": "Code inclus",
        "speed_level": "moyen",
        "speed_label": "7-11 semaines",
        "permis_type": "poids_lourd",
        "tags": [
            {"label": "Patient", "color": "blue"},
            {"label": "Flexible", "color": "blue"},
            {"label": "Dispo demain", "color": "green"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600&auto=format&fit=crop",
    },
    {
        "name": "Permis Horizon",
        "city": "Paris",
        "postal_code": "75011",
        "address": "22 rue de Charonne, Paris 11e",
        "lat": 48.8532,
        "lng": 2.3721,
        "rating": 4.7,
        "price": 930,
        "price_label": "Forfait 25h",
        "speed_level": "rapide",
        "speed_label": "4-6 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Examen blanc", "color": "blue"},
            {"label": "Boîte Manuelle", "color": "blue"},
            {"label": "Dispo rapide", "color": "green"},
        ],
        "image_url": "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?w=600&auto=format&fit=crop",
    },
    {
        "name": "Auto-École République",
        "city": "Paris",
        "postal_code": "75010",
        "address": "8 avenue de la République, Paris 10e",
        "lat": 48.8682,
        "lng": 2.3635,
        "rating": 4.4,
        "price": 790,
        "price_label": "Code + conduite",
        "speed_level": "moyen",
        "speed_label": "7-9 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Boîte Auto", "color": "blue"},
            {"label": "Soir et week-end", "color": "orange"},
        ],
        "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop",
    },
    {
        "name": "Académie Bastille",
        "city": "Paris",
        "postal_code": "75012",
        "address": "41 rue du Faubourg Saint-Antoine, Paris 12e",
        "lat": 48.8508,
        "lng": 2.3714,
        "rating": 4.6,
        "price": 1020,
        "price_label": "Forfait intensif",
        "speed_level": "rapide",
        "speed_label": "3-5 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "CPF", "color": "green"},
            {"label": "Boîte Auto", "color": "blue"},
            {"label": "Intensif", "color": "orange"},
        ],
        "image_url": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&auto=format&fit=crop",
    },
    {
        "name": "Conduite Montmartre",
        "city": "Paris",
        "postal_code": "75018",
        "address": "17 rue Lepic, Paris 18e",
        "lat": 48.8861,
        "lng": 2.3378,
        "rating": 4.2,
        "price": 710,
        "price_label": "Formule éco",
        "speed_level": "faible",
        "speed_label": "11-15 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Petit budget", "color": "green"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=600&auto=format&fit=crop",
    },
    {
        "name": "Drive Levallois",
        "city": "Levallois-Perret",
        "postal_code": "92300",
        "address": "12 rue Louise Michel, Levallois-Perret",
        "lat": 48.8935,
        "lng": 2.2868,
        "rating": 4.5,
        "price": 840,
        "price_label": "Forfait 20h",
        "speed_level": "moyen",
        "speed_label": "6-9 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Pédagogie", "color": "blue"},
            {"label": "Boîte Auto", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop",
    },
    {
        "name": "École Voltaire",
        "city": "Paris",
        "postal_code": "75011",
        "address": "73 boulevard Voltaire, Paris 11e",
        "lat": 48.8628,
        "lng": 2.3769,
        "rating": 4.9,
        "price": 1150,
        "price_label": "Premium express",
        "speed_level": "rapide",
        "speed_label": "2-4 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Premium", "color": "orange"},
            {"label": "CPF", "color": "green"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1508974239320-0a029497e820?w=600&auto=format&fit=crop",
    },
    {
        "name": "Conduite Nanterre",
        "city": "Nanterre",
        "postal_code": "92000",
        "address": "5 avenue Joliot-Curie, Nanterre",
        "lat": 48.8921,
        "lng": 2.2065,
        "rating": 4.1,
        "price": 690,
        "price_label": "Formule budget",
        "speed_level": "faible",
        "speed_label": "12-16 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Budget", "color": "green"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1549924231-f129b911e442?w=600&auto=format&fit=crop",
    },
    {
        "name": "Auto-École Clichy",
        "city": "Clichy",
        "postal_code": "92110",
        "address": "44 boulevard Jean Jaurès, Clichy",
        "lat": 48.9035,
        "lng": 2.3052,
        "rating": 4.3,
        "price": 770,
        "price_label": "Code inclus",
        "speed_level": "moyen",
        "speed_label": "7-10 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Boîte Auto", "color": "blue"},
            {"label": "Créneaux midi", "color": "orange"},
        ],
        "image_url": "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=600&auto=format&fit=crop",
    },
    {
        "name": "Permis Saint-Denis",
        "city": "Saint-Denis",
        "postal_code": "93200",
        "address": "3 place du Caquet, Saint-Denis",
        "lat": 48.9364,
        "lng": 2.3578,
        "rating": 4.0,
        "price": 680,
        "price_label": "Facilité de paiement",
        "speed_level": "faible",
        "speed_label": "12-18 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Paiement en plusieurs fois", "color": "green"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?w=600&auto=format&fit=crop",
    },
    {
        "name": "Montreuil Conduite",
        "city": "Montreuil",
        "postal_code": "93100",
        "address": "28 rue de Paris, Montreuil",
        "lat": 48.8615,
        "lng": 2.4416,
        "rating": 4.4,
        "price": 860,
        "price_label": "CPF + conduite",
        "speed_level": "moyen",
        "speed_label": "7-11 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "CPF", "color": "green"},
            {"label": "Boîte Auto", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=600&auto=format&fit=crop",
    },
    {
        "name": "Courbevoie Drive",
        "city": "Courbevoie",
        "postal_code": "92400",
        "address": "9 rue de Bezons, Courbevoie",
        "lat": 48.8972,
        "lng": 2.2568,
        "rating": 4.6,
        "price": 980,
        "price_label": "Pack réussite",
        "speed_level": "rapide",
        "speed_label": "4-6 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Premium", "color": "orange"},
            {"label": "Boîte Auto", "color": "blue"},
            {"label": "Dispo rapide", "color": "green"},
        ],
        "image_url": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=600&auto=format&fit=crop",
    },
    {
        "name": "Créteil Formation",
        "city": "Créteil",
        "postal_code": "94000",
        "address": "14 avenue du Général de Gaulle, Créteil",
        "lat": 48.7896,
        "lng": 2.4554,
        "rating": 4.1,
        "price": 730,
        "price_label": "Forfait week-end",
        "speed_level": "moyen",
        "speed_label": "8-11 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Week-end", "color": "orange"},
            {"label": "Boîte Manuelle", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1493238792000-8113da705763?w=600&auto=format&fit=crop",
    },
    {
        "name": "Antony Route",
        "city": "Antony",
        "postal_code": "92160",
        "address": "6 avenue Aristide Briand, Antony",
        "lat": 48.7533,
        "lng": 2.2962,
        "rating": 4.3,
        "price": 760,
        "price_label": "Code + 20h",
        "speed_level": "moyen",
        "speed_label": "7-10 semaines",
        "permis_type": "voiture",
        "tags": [
            {"label": "Boîte Auto", "color": "blue"},
            {"label": "Suivi personnalisé", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&auto=format&fit=crop",
    },
    {
        "name": "Moto School Nation",
        "city": "Paris",
        "postal_code": "75012",
        "address": "57 boulevard de Picpus, Paris 12e",
        "lat": 48.8472,
        "lng": 2.3964,
        "rating": 4.8,
        "price": 1190,
        "price_label": "Passerelle A2",
        "speed_level": "rapide",
        "speed_label": "4-6 semaines",
        "permis_type": "moto",
        "tags": [
            {"label": "Plateau inclus", "color": "orange"},
            {"label": "Équipement prêt", "color": "green"},
        ],
        "image_url": "https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=600&auto=format&fit=crop",
    },
    {
        "name": "Piste Moto 92",
        "city": "Puteaux",
        "postal_code": "92800",
        "address": "18 rue Jean Jaurès, Puteaux",
        "lat": 48.8842,
        "lng": 2.2391,
        "rating": 4.5,
        "price": 1080,
        "price_label": "Forfait A2",
        "speed_level": "moyen",
        "speed_label": "6-8 semaines",
        "permis_type": "moto",
        "tags": [
            {"label": "Piste privée", "color": "orange"},
            {"label": "Cours du soir", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1517846693594-1567da72af75?w=600&auto=format&fit=crop",
    },
    {
        "name": "Moto Academy Montreuil",
        "city": "Montreuil",
        "postal_code": "93100",
        "address": "105 rue de Rosny, Montreuil",
        "lat": 48.8634,
        "lng": 2.4447,
        "rating": 4.4,
        "price": 990,
        "price_label": "Stage permis A2",
        "speed_level": "faible",
        "speed_label": "9-12 semaines",
        "permis_type": "moto",
        "tags": [
            {"label": "Financement", "color": "green"},
            {"label": "Stage code", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1529421306624-54a114f0b9af?w=600&auto=format&fit=crop",
    },
    {
        "name": "Centre PL Rungis",
        "city": "Rungis",
        "postal_code": "94150",
        "address": "12 avenue Charles Lindbergh, Rungis",
        "lat": 48.7483,
        "lng": 2.3492,
        "rating": 4.6,
        "price": 1540,
        "price_label": "FIMO + permis",
        "speed_level": "moyen",
        "speed_label": "6-10 semaines",
        "permis_type": "poids_lourd",
        "tags": [
            {"label": "Simulation", "color": "blue"},
            {"label": "Entreprise", "color": "orange"},
        ],
        "image_url": "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=600&auto=format&fit=crop",
    },
    {
        "name": "Convoi Pro Gennevilliers",
        "city": "Gennevilliers",
        "postal_code": "92230",
        "address": "27 route du Bassin, Gennevilliers",
        "lat": 48.9336,
        "lng": 2.3095,
        "rating": 4.3,
        "price": 1590,
        "price_label": "Stage intensif C",
        "speed_level": "rapide",
        "speed_label": "5-7 semaines",
        "permis_type": "poids_lourd",
        "tags": [
            {"label": "Intensif", "color": "orange"},
            {"label": "Plateforme logistique", "color": "blue"},
        ],
        "image_url": "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop",
    },
]

LIBS = [
    {"key": "calculateur.status.lyceen", "fr": "Lycéen", "en": "High School Student"},
    {"key": "calculateur.status.etudiant", "fr": "Étudiant", "en": "Student"},
    {"key": "calculateur.status.apprenti", "fr": "Apprenti", "en": "Apprentice"},
    {"key": "calculateur.status.salarie", "fr": "Salarié", "en": "Employee"},
    {"key": "calculateur.status.chomeur", "fr": "Demandeur d'emploi", "en": "Job seeker"},
    {"key": "calculateur.status.autre", "fr": "Autre", "en": "Other"},
    {"key": "calculateur.error.age_missing", "fr": "Veuillez renseigner votre âge.", "en": "Please enter your age."},
    {"key": "calculateur.error.age_invalid", "fr": "Âge invalide.", "en": "Invalid age."},
    {"key": "calculateur.error.cp_missing", "fr": "Veuillez renseigner votre code postal.", "en": "Please enter your postal code."},
    {"key": "calculateur.error.cp_invalid", "fr": "Le code postal doit contenir 5 chiffres.", "en": "The postal code must contain 5 digits."},
    {"key": "calculateur.error.status_missing", "fr": "Veuillez sélectionner un statut.", "en": "Please select a status."},
    {"key": "calculateur.error.api", "fr": "Erreur de l'API", "en": "API Error"},
    {"key": "calculateur.error.api_fetch", "fr": "Impossible de calculer vos aides pour le moment. Veuillez réessayer plus tard.", "en": "Unable to calculate your aids at the moment. Please try again later."},
    {"key": "calculateur.title", "fr": "Calculateur d'aides", "en": "Aids Calculator"},
    {"key": "calculateur.subtitle", "fr": "Découvrez en 2 minutes les financements auxquels vous avez droit pour votre permis de conduire.", "en": "Discover in 2 minutes the financing you are entitled to for your driver's license."},
    {"key": "calculateur.step1", "fr": "1. Profil", "en": "1. Profile"},
    {"key": "calculateur.step2", "fr": "2. Situation", "en": "2. Situation"},
    {"key": "calculateur.label.age", "fr": "Quel est votre âge ?", "en": "What is your age?"},
    {"key": "calculateur.placeholder.age", "fr": "Ex: 18", "en": "Ex: 18"},
    {"key": "calculateur.label.cp", "fr": "Code postal de votre lieu de résidence", "en": "Postal code of your residence"},
    {"key": "calculateur.desc.cp", "fr": "Certaines aides dépendent de votre région ou département.", "en": "Some aids depend on your region or department."},
    {"key": "calculateur.placeholder.cp", "fr": "Ex: 75001", "en": "Ex: 75001"},
    {"key": "calculateur.btn.next", "fr": "Suivant", "en": "Next"},
    {"key": "calculateur.label.status", "fr": "Quelle est votre situation principale ?", "en": "What is your main situation?"},
    {"key": "calculateur.btn.submit", "fr": "Voir mes aides", "en": "See my aids"},
    {"key": "calculateur.result.title", "fr": "Voici les aides auxquelles vous pourriez avoir droit", "en": "Here are the aids you might be entitled to"},
    {"key": "calculateur.result.subtitle_part1", "fr": "Basé sur votre profil, vous pourriez économiser jusqu'à ", "en": "Based on your profile, you could save up to "},
    {"key": "calculateur.result.default_category", "fr": "Aide", "en": "Aid"},
    {"key": "calculateur.result.how_to_apply", "fr": "Comment en faire la demande", "en": "How to apply"},
    {"key": "calculateur.result.no_aides", "fr": "Désolé, aucune aide ne semble correspondre à votre profil actuel.", "en": "Sorry, no aid seems to match your current profile."},
    {"key": "calculateur.btn.compare", "fr": "Comparer les auto-écoles", "en": "Compare driving schools"},
    {"key": "calculateur.btn.recalculate", "fr": "Recalculer mon profil", "en": "Recalculate my profile"},
    {"key": "hero.badge", "fr": "100% Indépendant & Gratuit", "en": "100% Independent & Free"},
    {"key": "hero.title.part1", "fr": "Trouvez la meilleure auto-école et les aides pour ", "en": "Find the best driving school and aids to "},
    {"key": "hero.title.part2", "fr": "financer votre permis.", "en": "finance your driver's license."},
    {"key": "hero.subtitle", "fr": "Ne passez pas à côté de vos financements. Comparez les prix, vérifiez votre éligibilité aux aides, et choisissez votre auto-école en toute confiance.", "en": "Don't miss out on your financing. Compare prices, check your eligibility for aids, and choose your driving school with confidence."},
    {"key": "hero.btn.estimate", "fr": "Estimer mes aides (Gratuit)", "en": "Estimate my aids (Free)"},
    {"key": "hero.social_proof.count", "fr": "+10k", "en": "+10k"},
    {"key": "hero.social_proof.text", "fr": "Rejoint par +10 000 candidats", "en": "Joined by 10,000+ candidates"},
    {"key": "hero.simulator.title", "fr": "Simulateur rapide", "en": "Quick simulator"},
    {"key": "hero.simulator.subtitle", "fr": "Découvrez le montant de vos aides en 2 clics.", "en": "Discover the amount of your aids in 2 clicks."},
    {"key": "hero.simulator.age_label", "fr": "Votre âge :", "en": "Your age:"},
    {"key": "hero.simulator.status_label", "fr": "Votre situation :", "en": "Your situation:"},
    {"key": "hero.simulator.status.select", "fr": "Sélectionnez...", "en": "Select..."},
    {"key": "hero.simulator.status.etudiant", "fr": "Étudiant", "en": "Student"},
    {"key": "hero.simulator.status.apprenti", "fr": "Apprenti (- de 21 ans)", "en": "Apprentice (under 21)"},
    {"key": "hero.simulator.status.chomeur", "fr": "Demandeur d'emploi", "en": "Job seeker"},
    {"key": "hero.simulator.status.salarie", "fr": "Salarié", "en": "Employee"},
    {"key": "hero.simulator.result.label", "fr": "Aide estimée au permis", "en": "Estimated aid for the license"},
    {"key": "hero.simulator.result.disclaimer", "fr": "Montant purement indicatif. Cliquez sur le bouton pour faire une simulation complète et précise.", "en": "Purely indicative amount. Click the button to run a complete and accurate simulation."},
    {"key": "hero.aid.default", "fr": "--- €", "en": "--- €"},
    {"key": "hero.aid.apprenti", "fr": "500 €", "en": "500 €"},
    {"key": "hero.aid.chomeur", "fr": "Jusqu'à 1200 €", "en": "Up to 1200 €"},
    {"key": "hero.aid.jeune", "fr": "Jusqu'à 300 €", "en": "Up to 300 €"},
    {"key": "hero.aid.autre", "fr": "Jusqu'à 800 €", "en": "Up to 800 €"},
    {"key": "pillars.main_title", "fr": "Trois repères pour choisir sans angle mort.", "en": "Three benchmarks to choose with no blind spots."},
    {"key": "pillars.main_desc", "fr": "Nous vous offrons une transparence totale sur les prix, une centralisation de vos aides, et une vue claire sur les délais pour vous aider à faire le meilleur choix.", "en": "We offer total transparency on prices, centralization of your aids, and a clear view of deadlines to help you make the best choice."},
    {"key": "pillars.1.title", "fr": "Prix et délais lisibles", "en": "Clear prices and deadlines"},
    {"key": "pillars.1.desc", "fr": "Comparer les forfaits, les délais moyens et les critères qui changent vraiment le budget final.", "en": "Compare packages, average deadlines, and criteria that actually affect the final budget."},
    {"key": "pillars.2.title", "fr": "Aides en 2 minutes", "en": "Aids in 2 minutes"},
    {"key": "pillars.2.desc", "fr": "Estimer les financements possibles selon votre profil et lancer la première étape depuis le calculateur.", "en": "Estimate possible financing according to your profile and start the first step right from the calculator."},
    {"key": "pillars.3.title", "fr": "Indice de rapidité", "en": "Speed index"},
    {"key": "pillars.3.desc", "fr": "Classer les auto-écoles selon la réactivité et le délai réel avant l'examen.", "en": "Rank driving schools based on responsiveness and actual wait times before the exam."},
    {"key": "about.help.financing.title", "fr": "Aides au financement", "en": "Financing aids"},
    {"key": "about.help.financing.desc", "fr": "CPF, paiements fractionnés et offres promotionnelles des auto-écoles partenaires.", "en": "CPF, split payments, and promotional offers from partner driving schools."},
    {"key": "about.help.location.title", "fr": "Choix par localisation", "en": "Choice by location"},
    {"key": "about.help.location.desc", "fr": "Comparez les établissements proches de chez vous ou autour de votre position actuelle.", "en": "Compare establishments near you or around your current position."},
    {"key": "about.help.comparison.title", "fr": "Comparaison simplifiée", "en": "Simplified comparison"},
    {"key": "about.help.comparison.desc", "fr": "Budget, délai, type de permis et boîte de vitesse sont regroupés au même endroit.", "en": "Budget, timeframe, license type, and gearbox are grouped in one place."},
    {"key": "about.badge", "fr": "Aides", "en": "Aids"},
    {"key": "about.title", "fr": "Financer et choisir son auto-école plus sereinement", "en": "Finance and choose your driving school more serenely"},
    {"key": "about.subtitle", "fr": "Cette page évite le 404 du menu et pose la base de l'espace aides du produit.", "en": "This page avoids the 404 from the menu and lays the foundation for the product's aids section."},
    {"key": "about.btn.back", "fr": "Retour au comparateur", "en": "Back to comparator"},
    {"key": "comparer.permit.all", "fr": "Tous", "en": "All"},
    {"key": "comparer.permit.voiture", "fr": "Voiture (B)", "en": "Car (B)"},
    {"key": "comparer.permit.moto", "fr": "Moto (A)", "en": "Motorcycle (A)"},
    {"key": "comparer.permit.poids_lourd", "fr": "Poids lourd (C)", "en": "Heavy Vehicle (C)"},
    {"key": "comparer.sort.score", "fr": "Score", "en": "Score"},
    {"key": "comparer.sort.asc", "fr": "Prix bas", "en": "Low price"},
    {"key": "comparer.sort.desc", "fr": "Prix haut", "en": "High price"},
    {"key": "comparer.score.all", "fr": "Tous", "en": "All"},
    {"key": "comparer.score.all.helper", "fr": "Aucun minimum", "en": "No minimum"},
    {"key": "comparer.score.70.helper", "fr": "Bon match", "en": "Good match"},
    {"key": "comparer.score.80.helper", "fr": "Très bon", "en": "Very good"},
    {"key": "comparer.score.90.helper", "fr": "Excellent", "en": "Excellent"},
    {"key": "comparer.gear.all", "fr": "Toutes", "en": "All"},
    {"key": "comparer.gear.auto", "fr": "Boîte auto", "en": "Auto gearbox"},
    {"key": "comparer.gear.manuelle", "fr": "Boîte manuelle", "en": "Manual gearbox"},
    {"key": "comparer.card.score", "fr": "Score", "en": "Score"},
    {"key": "comparer.card.quote", "fr": "Devis", "en": "Quote"},
    {"key": "comparer.card.package", "fr": "Forfait", "en": "Package"},
    {"key": "comparer.card.calculated", "fr": "Score calculé avec prix, note, délai et distance.", "en": "Score calculated with price, rating, delay, and distance."},
    {"key": "comparer.card.details", "fr": "Voir détails", "en": "View details"},
    {"key": "comparer.match.90", "fr": "90+ Excellent", "en": "90+ Excellent"},
    {"key": "comparer.match.80", "fr": "80+ Très bon", "en": "80+ Very good"},
    {"key": "comparer.match.70", "fr": "70+ Bon", "en": "70+ Good"},
    {"key": "comparer.match.default", "fr": "À comparer", "en": "To compare"},
    {"key": "comparer.reasons.speed_fast", "fr": "Délai rapide", "en": "Fast delay"},
    {"key": "comparer.reasons.speed_medium", "fr": "Délai maîtrisé", "en": "Controlled delay"},
    {"key": "comparer.reasons.rating_excellent", "fr": "Très bien notée", "en": "Highly rated"},
    {"key": "comparer.reasons.rating_good", "fr": "Bonne note", "en": "Good rating"},
    {"key": "comparer.reasons.price_competitive", "fr": "Prix compétitif", "en": "Competitive price"},
    {"key": "comparer.reasons.price_high", "fr": "Budget plus élevé", "en": "Higher budget"},
    {"key": "comparer.reasons.distance_very_close", "fr": "Très proche", "en": "Very close"},
    {"key": "comparer.reasons.distance_close", "fr": "Proche", "en": "Close"},
    {"key": "comparer.filter.score.title", "fr": "Score global", "en": "Global score"},
    {"key": "comparer.filter.score.hint", "fr": "Prix, note, délai et distance pondérés ensemble.", "en": "Price, rating, delay, and distance weighted together."},
    {"key": "comparer.filter.radius.title", "fr": "Rayon d'action", "en": "Action radius"},
    {"key": "comparer.filter.radius.hint_active", "fr": "Autour de", "en": "Around"},
    {"key": "comparer.filter.radius.hint_inactive", "fr": "Choisissez une adresse pour activer le rayon.", "en": "Choose an address to activate the radius."},
    {"key": "comparer.filter.radius.max", "fr": "max", "en": "max"},
    {"key": "comparer.filter.radius.inactive", "fr": "inactif", "en": "inactive"},
    {"key": "comparer.filter.budget.title", "fr": "Budget", "en": "Budget"},
    {"key": "comparer.filter.budget.hint", "fr": "Fourchette minimum et maximum.", "en": "Minimum and maximum range."},
    {"key": "comparer.filter.permit.title", "fr": "Type de permis", "en": "License type"},
    {"key": "comparer.filter.permit.hint", "fr": "Voiture, moto ou poids lourd.", "en": "Car, motorcycle, or heavy vehicle."},
    {"key": "comparer.filter.sort.title", "fr": "Tri", "en": "Sort"},
    {"key": "comparer.filter.sort.hint", "fr": "Score par défaut, prix si besoin.", "en": "Score by default, price if needed."},
    {"key": "comparer.filter.gear.title", "fr": "Boîte", "en": "Gearbox"},
    {"key": "comparer.filter.gear.hint", "fr": "Automatique ou manuelle.", "en": "Automatic or manual."},
    {"key": "comparer.filter.reset", "fr": "Réinitialiser les filtres", "en": "Reset filters"},
    {"key": "comparer.filter.reset_short", "fr": "Réinitialiser", "en": "Reset"},
    {"key": "comparer.filter.default", "fr": "Filtres par défaut", "en": "Default filters"},
    {"key": "comparer.filter.updating", "fr": "Mise à jour...", "en": "Updating..."},
    {"key": "comparer.filter.result", "fr": "résultat", "en": "result"},
    {"key": "comparer.filter.results", "fr": "résultats", "en": "results"},
    {"key": "comparer.filter.close", "fr": "Fermer", "en": "Close"},
    {"key": "comparer.mobile_sheet.title", "fr": "Filtres", "en": "Filters"},
    {"key": "comparer.mobile_sheet.subtitle", "fr": "Score, rayon, budget et boîte.", "en": "Score, radius, budget, and gearbox."},
    {"key": "comparer.cards_area.error", "fr": "Impossible de charger les auto-écoles. Vérifiez l'API et votre connexion.", "en": "Unable to load driving schools. Check the API and your connection."},
    {"key": "comparer.cards_area.empty_1", "fr": "Aucune auto-école trouvée avec ces critères.", "en": "No driving school found with these criteria."},
    {"key": "comparer.cards_area.empty_2", "fr": "Essayez d'élargir le budget, le rayon ou le score minimum.", "en": "Try to widen the budget, the radius, or the minimum score."},
    {"key": "comparer.page.filters", "fr": "Filtres", "en": "Filters"},
    {"key": "comparer.page.results_near", "fr": "Résultats près de", "en": "Results near"},
    {"key": "comparer.page.results_score", "fr": "Résultats par score", "en": "Results by score"},
    {"key": "comparer.page.title", "fr": "Comparer les auto-écoles", "en": "Compare driving schools"},
    {"key": "comparer.page.results_count", "fr": "Résultats", "en": "Results"},
    {"key": "comparer.page.active_address", "fr": "Adresse active", "en": "Active address"},
    {"key": "comparer.page.active_address_desc_1", "fr": "Les résultats sont calculés autour de", "en": "Results are calculated around"},
    {"key": "comparer.page.inactive_address_desc", "fr": "Saisissez une adresse ou utilisez votre position pour activer le rayon. Sans adresse, le classement reste basé sur le score global.", "en": "Enter an address or use your position to activate the radius. Without an address, the ranking remains based on the global score."},
    {"key": "comparer.page.address", "fr": "Adresse", "en": "Address"},
    {"key": "comparer.page.desktop_title", "fr": "Trouvez l'établissement qui coche les bons critères", "en": "Find the establishment that ticks the right boxes"},
    {"key": "comparer.page.desktop_subtitle", "fr": "Adresse précise, rayon, budget et score global dans une interface plus lisible pour comparer vite.", "en": "Precise address, radius, budget, and global score in a more readable interface to compare quickly."},
    {"key": "comparer.page.desktop_schools", "fr": "Auto-écoles", "en": "Driving schools"},
    {"key": "comparer.page.radius_inactive", "fr": "Rayon inactif", "en": "Inactive radius"},
    {"key": "comparer.page.radius_inactive_desc", "fr": "Choisissez une adresse complète pour activer la proximité. Le classement actuel privilégie le score global.", "en": "Choose a complete address to activate proximity. The current ranking favors the overall score."},
    {"key": "comparer.summary.radius", "fr": "Rayon", "en": "Radius"},
    {"key": "comparer.summary.score", "fr": "Score", "en": "Score"},
    {"key": "comparer.summary.low_price", "fr": "Prix bas", "en": "Low price"},
    {"key": "comparer.summary.high_price", "fr": "Prix haut", "en": "High price"},
    {"key": "comparer.summary.auto", "fr": "Boîte auto", "en": "Auto gearbox"},
    {"key": "comparer.summary.manual", "fr": "Boîte manuelle", "en": "Manual gearbox"},
    {"key": "comparer.summary.sort_score", "fr": "Tri score", "en": "Sort by score"},
    {"key": "comparer.summary.gearbox", "fr": "Boîte", "en": "Gearbox"},
    {"key": "calculateur.status.jeune_insertion", "fr": "Jeune en insertion", "en": "Youth in integration"},
    {"key": "calculateur.status.interimaire", "fr": "Intérimaire", "en": "Temporary worker"},
    {"key": "calculateur.status.reserve_militaire", "fr": "Réserviste", "en": "Military reservist"},
    {"key": "calculateur.status.snu", "fr": "SNU", "en": "SNU (Universal National Service)"},
    {"key": "calculator_form.profile.title", "fr": "Votre profil", "en": "Your profile"},
    {"key": "calculator_form.profile.age", "fr": "Âge", "en": "Age"},
    {"key": "calculator_form.profile.region", "fr": "Région", "en": "Region"},
    {"key": "calculator_form.profile.status", "fr": "Statut actuel", "en": "Current status"},
    {"key": "calculator_form.specific.title", "fr": "Situations spécifiques", "en": "Specific situations"},
    {"key": "calculator_form.specific.rqth", "fr": "Êtes-vous en situation de handicap (RQTH) ?", "en": "Are you in a situation of disability (RQTH)?"},
    {"key": "calculator_form.specific.boursier", "fr": "Êtes-vous étudiant boursier ?", "en": "Are you a scholarship student?"},
    {"key": "calculator_form.specific.france_travail", "fr": "Êtes-vous inscrit à France Travail ?", "en": "Are you registered with France Travail?"},
    {"key": "calculator_form.specific.rsa", "fr": "Êtes-vous bénéficiaire du RSA ?", "en": "Are you a RSA beneficiary?"},
    {"key": "calculator_form.specific.formation", "fr": "Suivez-vous une formation qualifiante ?", "en": "Are you undergoing qualifying training?"},
    {"key": "calculator_form.btn.yes", "fr": "Oui", "en": "Yes"},
    {"key": "calculator_form.btn.no", "fr": "Non", "en": "No"},
    {"key": "calculator_form.btn.calculating", "fr": "Calcul en cours...", "en": "Calculating..."},
    {"key": "calculator_form.btn.estimate", "fr": "Estimer mes aides", "en": "Estimate my aids"},
    {"key": "calculator_results.total_potential", "fr": "Total potentiel des aides", "en": "Total potential aids"},
    {"key": "calculator_results.details_title", "fr": "Détails des aides éligibles", "en": "Details of eligible aids"},
    {"key": "calculator_results.view_details", "fr": "VOIR LES DÉTAILS", "en": "VIEW DETAILS"},
    {"key": "calculator_results.no_aids_found", "fr": "Aucune aide trouvée pour votre profil actuel.", "en": "No aids found for your current profile."},
    {"key": "calculator_results.disclaimer", "fr": "Cette simulation est basée sur les données publiques disponibles en 2026. Elle est fournie à titre indicatif et ne constitue pas une garantie d'obtention. Les critères réels et les montants finaux doivent être validés auprès des organismes officiels.", "en": "This simulation is based on public data available in 2026. It is provided for indicative purposes and does not constitute a guarantee of obtaining them. The actual criteria and final amounts must be validated with the official organizations."},
    {"key": "navbar.comparer", "fr": "Comparer", "en": "Compare"},
    {"key": "navbar.aides", "fr": "Aides", "en": "Aids"},
    {"key": "navbar.compte", "fr": "Compte", "en": "Account"},
    {"key": "compte.greeting", "fr": "Bonjour", "en": "Hello"},
    {"key": "compte.welcome", "fr": "Bienvenue sur votre espace personnel.", "en": "Welcome to your personal space."},
    {"key": "compte.logout", "fr": "Se déconnecter", "en": "Log out"},
    {"key": "compte.info.title", "fr": "Mes informations", "en": "My information"},
    {"key": "compte.info.fullname", "fr": "Nom complet", "en": "Full name"},
    {"key": "compte.info.email", "fr": "Email", "en": "Email"},
    {"key": "compte.info.phone", "fr": "Téléphone", "en": "Phone"},
    {"key": "compte.info.age", "fr": "Âge", "en": "Age"},
    {"key": "compte.info.years", "fr": "ans", "en": "years"},
    {"key": "compte.info.status", "fr": "Statut", "en": "Status"},
    {"key": "compte.info.postal_code", "fr": "Code Postal", "en": "Postal Code"},
    {"key": "compte.soon", "fr": "Bientôt", "en": "Coming soon"},
    {"key": "compte.favorites.title", "fr": "Auto-écoles favorites", "en": "Favorite driving schools"},
    {"key": "compte.favorites.desc", "fr": "Vous pourrez bientôt sauvegarder vos auto-écoles préférées pour les comparer plus facilement et les retrouver sur tous vos appareils.", "en": "You will soon be able to save your favorite driving schools to compare them more easily and find them on all your devices."},
    {"key": "compte.favorites.empty", "fr": "Vous n'avez pas encore d'auto-école favorite. Cliquez sur le ❤️ d'une auto-école pour l'enregistrer.", "en": "You don't have any favorite driving school yet. Click the ❤️ on a driving school to save it."},
    {"key": "compte.history.title", "fr": "Historique des recherches", "en": "Search history"},
    {"key": "compte.history.desc", "fr": "Retrouvez facilement les résultats de vos précédentes recherches et calculs d'aides CPF / Pôle Emploi.", "en": "Easily find the results of your previous searches and CPF / Pôle Emploi aid calculations."},
    {"key": "compte.history.empty", "fr": "Aucune recherche enregistrée pour le moment.", "en": "No saved search yet."},
    {"key": "compte.history.potential", "fr": "Aides potentielles", "en": "Potential aids"},
    {"key": "compte.history.aides_count", "fr": "aide(s) éligible(s)", "en": "eligible aid(s)"},
    {"key": "auth.error.unexpected", "fr": "Une erreur inattendue est survenue, veuillez réessayer plus tard.", "en": "An unexpected error occurred, please try again later."},
    {"key": "auth.error.validation", "fr": "Le format de certaines informations est incorrect. Veuillez vérifier votre saisie.", "en": "The format of some information is incorrect. Please check your entry."},
    {"key": "auth.error.user_not_found", "fr": "Aucun compte n'a été trouvé avec cette adresse e-mail.", "en": "No account was found with this email address."},
    {"key": "auth.error.email_registered", "fr": "Cette adresse e-mail est déjà utilisée.", "en": "This email address is already in use."},
    {"key": "auth.error.otp_invalid", "fr": "Le code secret est incorrect ou a expiré.", "en": "The secret code is incorrect or has expired."},
    {"key": "auth.error.not_found", "fr": "Erreur technique : Adresse introuvable.", "en": "Technical error: Address not found."},
    {"key": "auth.title.login", "fr": "Connexion", "en": "Login"},
    {"key": "auth.title.register", "fr": "Inscription", "en": "Sign Up"},
    {"key": "auth.title.verify", "fr": "Vérification", "en": "Verification"},
    {"key": "auth.subtitle.login", "fr": "Entrez votre e-mail pour recevoir un code de connexion ou vous inscrire.", "en": "Enter your email to receive a login code or to sign up."},
    {"key": "auth.subtitle.register", "fr": "On dirait que vous êtes nouveau ! Complétons votre profil avant de continuer.", "en": "Looks like you're new here! Let's complete your profile before continuing."},
    {"key": "auth.subtitle.verify_part1", "fr": "Nous avons envoyé un code secret à", "en": "We have sent a secret code to"},
    {"key": "auth.subtitle.verify_part2", "fr": "Entrez-le ci-dessous.", "en": "Enter it below."},
    {"key": "auth.placeholder.email", "fr": "nom@exemple.fr", "en": "name@example.com"},
    {"key": "auth.btn.continue", "fr": "Continuer", "en": "Continue"},
    {"key": "auth.placeholder.firstname", "fr": "Prénom", "en": "First name"},
    {"key": "auth.placeholder.lastname", "fr": "Nom", "en": "Last name"},
    {"key": "auth.placeholder.phone", "fr": "Numéro de téléphone", "en": "Phone number"},
    {"key": "auth.btn.register", "fr": "S'inscrire et recevoir le code", "en": "Sign up and receive code"},
    {"key": "auth.placeholder.otp", "fr": "Code à 6 chiffres", "en": "6-digit code"},
    {"key": "auth.btn.verify", "fr": "Vérifier et se connecter", "en": "Verify and log in"}
]

def seed():
    db = SessionLocal()
    try:
        # Seed auto-écoles
        existing_names = {
            name for (name,) in db.query(AutoEcole.name).all()
        }
        missing_ecoles = [
            AutoEcole(**data) for data in ECOLES if data["name"] not in existing_names
        ]

        if missing_ecoles:
            db.add_all(missing_ecoles)
            db.commit()
            print(f"[seed] {len(missing_ecoles)} auto-écoles insérées.")

        # Seed aides
        existing_aides = {
            nom for (nom,) in db.query(AideDB.nom).all()
        }
        missing_aides = [
            AideDB(**data) for data in AIDES if data["nom"] not in existing_aides
        ]

        if missing_aides:
            db.add_all(missing_aides)
            db.commit()
            print(f"[seed] {len(missing_aides)} aides insérées.")

        # Seed libs
        existing_libs = {
            key for (key,) in db.query(Lib.key).all()
        }
        missing_libs = [
            Lib(**data) for data in LIBS if data["key"] not in existing_libs
        ]

        if missing_libs:
            db.add_all(missing_libs)
            db.commit()
            print(f"[seed] {len(missing_libs)} traductions insérées.")
    finally:
        db.close()
